source 'https://github.com/CocoaPods/Specs.git'

target 'NNPickerController', :exclusive => true do
  pod "NNPickerController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NNPickerController", :path => "../"

  
end
