# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
- gem install cocoapods -r
- pod setup
- cd Example && pod install && cd -

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet    
# before_install: cd Example && pod install && cd -
script:
- set -o pipefail && xcodebuild test -workspace Example/NNPickerController.xcworkspace -scheme NNPickerController -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
